name: CI

on:
  push:
    branches: [latest]
  merge_group:
  pull_request:
    branches: [latest]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20
  ASTRO_TELEMETRY_DISABLED: true

jobs:
  test:
    # Skip for now — content layer example can’t fetch required resources in CI
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm t
